# Generated by Django 3.0.5 on 2020-04-26 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('roll', models.IntegerField(primary_key=True, serialize=False, verbose_name='Roll Number')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Libook',
            fields=[
                ('bid', models.CharField(db_column='Book Id', max_length=100, primary_key=True, serialize=False, verbose_name='Book Id')),
                ('bname', models.CharField(db_column='Book Name', max_length=100, verbose_name='Book Name')),
                ('bno', models.IntegerField(db_column='Total Book', verbose_name='Total Book')),
                ('avlbook', models.IntegerField(db_column='Available Book', verbose_name='Available Book')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False, verbose_name='Roll Number')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('bid', models.CharField(db_column='Book Id', max_length=100, primary_key=True, serialize=False, verbose_name='Book Id')),
                ('bname', models.CharField(db_column='Book Name', max_length=100, verbose_name='Book Name')),
                ('returndate', models.DateTimeField(auto_now=True, db_column='Return Date', verbose_name='Return Date')),
                ('roll', models.ForeignKey(db_column='Roll No', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Roll No')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(db_column='First Name', max_length=30, null=True, verbose_name='First Name')),
                ('lname', models.CharField(db_column='Last Name', max_length=30, null=True, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_column='Gender', max_length=6, null=True)),
                ('clss', models.CharField(choices=[('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], db_column='Class', max_length=4, null=True, verbose_name='Class')),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], db_column='Section', max_length=3, null=True)),
                ('img', models.ImageField(db_column='Profile Picture', null=True, upload_to='', verbose_name='Profile Picture')),
                ('dob', models.DateField(db_column='Date of Birth', null=True, verbose_name='Date of Birth')),
                ('datereg', models.DateTimeField(auto_now=True, db_column='Registeration Date', verbose_name='Registeration Date')),
                ('roll', models.OneToOneField(db_column='Roll No', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('bid', models.CharField(db_column='Book Id', max_length=100, primary_key=True, serialize=False, verbose_name='Book Id')),
                ('bname', models.CharField(db_column='Book Name', max_length=100, verbose_name='Book Name')),
                ('issuedate', models.DateTimeField(auto_now=True, db_column='Issued Date', verbose_name='Issued Date')),
                ('roll', models.ForeignKey(db_column='Roll No', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Roll No')),
            ],
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('roll', 'bname'), name='one_book'),
        ),
    ]
